"""
Author: Carter Spenner
Date: 3/23/2026
Purpose: To practice using if statements in Python.
"""

temperature = float(input("Enter the temperature in Fahrenheit: "))
if temperature > 85:
    print("Your guess was higher!")
elif temperature < 85:
    print("Your guess was lower!")
elif temperature == 85:
    print("Your guess was correct!")

username = "iusearchbtw"
password = "totallysecurepassword123"

username_input = input("Enter your username: ").strip().lower()
password_input = input("Enter your password: ")

if username_input == username and password_input == password:
        print("Login successful!")
else:
    print("Login failed. Please check your username and password.")

#CYOA Game (story generated by Claude)
print("Welcome to the adventure game!")

if input("You find yourself at a crossroads. Do you go left or right? (left/right): ").strip().lower() == "left":
    if input("You encounter a river. Do you swim through it or follow the riverbank? (swim/follow): ").strip().lower() == "swim":
        if input("You find yourself in a cave. Do you explore it or climb out? (explore/climb): ").strip().lower() == "explore":
            print("You find a hidden treasure! You win!")
        else:
            print("You survive and escape, but you feel like you left something behind... You didn't lose nor win, but at least you're alive.")

    else:
        if input("You follow the riverbank and find yourself at a troll bridge. Do you want to fight or try to sneak around? (fight/sneak): ").strip().lower() == "fight":
            print("You defeat the troll but get injured in the process. You lose!")
        else:
            print("You try to sneak around the troll, and make it successfully. While running, you spot a village and head over there. You win!")
else:
    if input("You find an old cabin in the distance. Do you enter it or avoid it? (enter/avoid): ").strip().lower() == "enter":
        if input("Inside sits an old wizard. Do you ask for his help or steal his staff? (ask/steal): ").strip().lower() == "ask":
            print("The wizard smiles and teleports you safely home. You win!")
        else:
            print("The wizard catches you and turns you into a frog. You lose!")
    else:
        if input("You wander deeper into the forest and get lost. Do you climb a tree to look around or wait for morning? (climb/wait): ").strip().lower() == "climb":
            print("From the treetop you spot a path leading out. You escape! You win!")
        else:
            print("Night falls and wolves surround you. You should have climbed that tree. You lose!")
